### ISSUE TITLE
[FNB] Laporan settlement pos filter by cashier 

### ISSUE THREAD

**Issue by chelsymooy** [HOTEL-KONTENA/HOME-KONTENA#12]

**Comment by chelsymooy** [comment]
![image](https://user-images.githubusercontent.com/5895063/120422533-acff8300-c392-11eb-82a2-ef86aef15b2a.png)

**Comment by chelsymooy** [comment]
@agilma tlong tambah laporan settlement pakai query POSSettlements
Isi sama seperti laporan FO - RECEIPT
FILTER: Tanggal (periode) - Opsi datetime, Metode - Opsi, Nama Cashier (cashier_name) - Free text

**Comment by chelsymooy** [comment]
query t1{
  POSSettlements(cashier_name:"Yohan") {
    data {
      id
      no
      type
      invoice{
        customer
      }
    }
  }
}

**Comment by agilma** [comment]
updated settlements https://github.com/ardiankurniawan8/Kontena-Dashboard/commit/019be8d6cc2b4bfdbe0c43f47ce560ae40ebce28

**Comment by chelsymooy** [comment]
mas @agilma  filter by methodnya blm ada

**Comment by agilma** [comment]
updated yaa utk methodnya  https://github.com/ardiankurniawan8/Kontena-Dashboard/commit/23ca0e9d66f02f85c7bc936351735daf5a2884db

**Comment by chelsymooy** [comment]
![image](https://user-images.githubusercontent.com/5895063/120593887-51082d80-c46a-11eb-90d1-71906c9abdd0.png)
