### ISSUE TITLE
[FO] Laporan receipt filter by cashier

### ISSUE THREAD

**Issue by chelsymooy** [HOTEL-KONTENA/HOME-KONTENA#13]

**Comment by chelsymooy** [comment]
@agilma 
FILTER: Tanggal (periode) - Opsi datetime, Metode - Opsi, Nama Cashier (cashier_name) - Free text

**Comment by chelsymooy** [comment]
query t2{
  Receipts(cashier_name:"Rhomy Nur Aji Nugroho") {
    data {
      id
      no
      method
    }
  }
}

**Comment by agilma** [comment]
updated https://github.com/ardiankurniawan8/Kontena-Dashboard/commit/d377ce7a666ca6b616e020acbf3e451fa6ca6ccd

**Comment by chelsymooy** [comment]
![image](https://user-images.githubusercontent.com/5895063/120605106-e1993a80-c477-11eb-8202-d668d088af78.png)
