### ISSUE TITLE
[FO, FNB] Detail receipt dari remittance 

### ISSUE THREAD

**Issue by chelsymooy** [HOTEL-KONTENA/HOME-KONTENA#14]
- [x] Dashboard
- [x] Apps Cashier

**Comment by chelsymooy** [comment]
@chelsymooy tambahkan method di query cashierlogs
@agilma  tolong bantu tambahkan breakdown cashier logs. kalau sudah selesai baru proceed apps

**Comment by chelsymooy** [comment]
query t3{
  CashierLogs(method: "CASH") {
    data {
      id
      method
    }
  }
}

**Comment by agilma** [comment]
updated https://github.com/ardiankurniawan8/Kontena-Dashboard/commit/d377ce7a666ca6b616e020acbf3e451fa6ca6ccd

**Comment by chelsymooy** [comment]
query t3{
CashierLogs(method: "CASH", casher_session_id: 1) {
data {
id
method
}
}
}
