### ISSUE TITLE
[CASHIER] Artikel yang sudah di void masih muncul laporan pembayaran

### ISSUE THREAD

**Issue by chelsymooy** [HOTEL-KONTENA/HOME-KONTENA#15]

**Comment by chelsymooy** [comment]
@hanaerliana29 tolong dibantu

**Comment by hanaerliana29** [comment]
masih ditanyakan ke pak jusuf kak

**Comment by hanaerliana29** [comment]
Dari Pak Hamdan : tanggal 22 Mei dan di NA masih ada recordnya
![WhatsApp Image 2021-05-31 at 17 14 27](https://user-images.githubusercontent.com/79246011/120179779-2ed99a00-c235-11eb-99b3-4a04a20634a4.jpeg)
![WhatsApp Image 2021-05-31 at 17 14 45](https://user-images.githubusercontent.com/79246011/120179840-47e24b00-c235-11eb-8fe6-acbad52bac49.jpeg)

**Comment by hanaerliana29** [comment]
Dari Pak Henry : Contoh transaksi 001. FO.2105.0532 tanggal 25 Mei, di laporan remittance total seharusnya 690.000 tapi karena divoid masih ikut terhitung jadi totalnya 855.000 (selisih void 165.000)
![WhatsApp Image 2021-05-31 at 17 26 55](https://user-images.githubusercontent.com/79246011/120179962-6ea08180-c235-11eb-92d5-d2d4d9566f90.jpeg)

**Comment by hanaerliana29** [comment]
@chelsymooy

**Comment by chelsymooy** [comment]
@hanaerliana29 tolong bantu test ya

CASE FO

- [x] Shift 1 buat deposit, tidak cancel. Remittance shift 1 +
- [x]  Shift 1 buat deposit, cancel di shift 1. Remittance shift 1 0.
- [x]  Shift 1 buat deposit, cancel di shift 2. Remittance shift 1 +, Remittance shift 2 -

CASE FB
- [x]  Shift 1 buat settlement, tidak cancel. Remittance shift 1 +
- [x]  Shift 1 buat settlement, cancel di shift 1. Remittance shift 1 0.
- [x] Shift 1 buat settlement, cancel di shift 2. Remittance shift 1 +, Remittance shift 2 -

**Comment by chelsymooy** [comment]
> Dari Pak Hamdan : tanggal 22 Mei dan di NA masih ada recordnya
> ![WhatsApp Image 2021-05-31 at 17 14 27](https://user-images.githubusercontent.com/79246011/120179779-2ed99a00-c235-11eb-99b3-4a04a20634a4.jpeg)
> ![WhatsApp Image 2021-05-31 at 17 14 45](https://user-images.githubusercontent.com/79246011/120179840-47e24b00-c235-11eb-8fe6-acbad52bac49.jpeg)

Untuk tanggal 22/05/21
Itu terjadi karena laporan cancel invoice setelah night audit yaitu jam 2021-05-23 05:56:12

**Comment by chelsymooy** [comment]
Untuk koreksi harusnya masuk report tanggal 23/05/21 sebagai transaksi -
