### ISSUE TITLE
[FO] BAGIAN NA DAPAT AKSES POS INVOICE

### ISSUE THREAD

**Issue by chelsymooy** [HOTEL-KONTENA/HOME-KONTENA#20]

**Comment by agilma** [comment]
tambah laporan pos invoice di FO https://github.com/ardiankurniawan8/Kontena-Dashboard/commit/8496a6f32c3a87a74da24959dfeea18a88a46655 

scope invoice delete & settlement delete sudah diberikan kepada anak FO yang laki

**Comment by agilma** [comment]
ini uda di ganti jadi POS Settlement 
https://github.com/ardiankurniawan8/Kontena-Dashboard/commit/23ca0e9d66f02f85c7bc936351735daf5a2884db

**Comment by chelsymooy** [comment]
![image](https://user-images.githubusercontent.com/5895063/120604374-32f4fa00-c477-11eb-875e-26ec23fae98f.png)
