### ISSUE TITLE
[FO] Kamar 1126, 1128 dan 1130 tidak masuk NA - ROOM REVENUE tanggal 8 Juni 2021

### ISSUE THREAD

**Issue by chelsymooy** [HOTEL-KONTENA/HOME-KONTENA#22]
Kontak tgl : 9 Juni 21
By: Jusuf AFOM

**Comment by chelsymooy** [comment]
Ini setelah kucheck room breakdownnya keliru, yaitu tanggal 7 JUNI 2021
seharusnya tanggal 8 JUNI 2021

Disistem belum pernah ada perubahan tentang room breakdown. Apakah bisa tolong di cek di UI untuk case:
1. Buat reservasi untuk tanggal H sampai tanggal H+1
2. Lalu diganti tanggal H+1 Sampai H+2

Apakah di dashboard, breakdown UI-nya data breakdown H atau berubah jadi H+1?
@agilma 


Dan @hanaerliana29 bisa tolong bantu di crosscheck data reservasi atas nama LIM HENNY LIDIA apakah memang diganti tanggalnya?

![image](https://user-images.githubusercontent.com/5895063/121628738-073fc880-caa4-11eb-9b17-0bb48adf3519.png)

**Comment by agilma** [comment]
berikut aku kasih video rekaman screen recorder local test klo room rate breakdownnya waktu edit reservasi, datanya juga ikut berubah yg di description room rate breakdownnya juga ikutan berubah
https://drive.google.com/file/d/1JQxRVjzP5mHPyFtEGF4UtP7Z4qyPbNMf/view?usp=sharing

**Comment by chelsymooy** [comment]
Kasus yang ini
reservasi tanggal 8-9 juni 2021
tapi room breakdownnya tanggal 7 juni 2021

karena room breakdown itu inputan makanya kuminta dicekkan dari dashboard
ada ga kemungkinan mereka edit dari fitur lain (misal pas mau checkin dkk)

**Comment by hanaerliana29** [comment]
@chelsymooy a.n LIM HENNY LIDIA kata FO, reservasi tanggal 07 Juni. Dan Check in tanggal 08 Juni. Dan seharusnya masuk di NA report tanggal 08, dan kamarnya tidak masuk room revenue

**Comment by chelsymooy** [comment]
@hanaerliana29 thanks, mas agil uda nemu error nya @agilma

**Comment by agilma** [comment]
updated ya, coba di test dulu sebelum pull, dicoba di local habis edit langsung di save formnya, lalu setelah itu pull. aku nemu bugnya disitu tadi. dan uda kutambahkan state disable button savenya klo masih loading componentnya.

**Comment by chelsymooy** [comment]
wkwkwk
jangan lupa ganti warna

**Comment by chelsymooy** [comment]
@hanaerliana29 Tolong dibantu follow up ke mas Jusuf

Error: Kamar 1126, 1128 dan 1130 tidak masuk NA - ROOM REVENUE tanggal 8 Juni 2021 ?
Kenapa: Karena rate breakdownnya tanggal 7 Juni 2021

Error: Kenapa rate breakdown bisa tanggal 7 Juni 2021 ? 
Kenapa: Kemungkinan masalah jaringan, masih sementara loading sudah di submit ke sistem sehingga datanya "cacat"
Solusi: Tidak bisa klik "save" sampai selesai loading

**Comment by hanaerliana29** [comment]
@chelsymooy baik kak
